dpm/apps/accounts/urls.py
from django.urls import path, include

from apps.accounts.views import RegistrationView, UserDeleteView

app_name = "accounts"

urlpatterns = [
    path("delete_account/", UserDeleteView.as_view(), name="delete_account"),
    path("", include("django.contrib.auth.urls")),
    path("register/", RegistrationView.as_view(), name="register")
]

dpm/apps/passwords/urls.py
from django.urls import path
from apps.passwords import views

app_name = "passwords"

urlpatterns = [
    path("", views.EntryView.as_view(), name="vault"),
    path("entries/new", views.EntryCreateView.as_view(), name="new"),
    path("entries/<int:pk>/edit", views.EntryUpdateView.as_view(), name="edit"),
    path("entries/<int:pk>/delete/", views.EntryDeleteView.as_view(), name="delete"),
    path("new_folder", views.FolderCreateView.as_view(), name="new_folder"),
]

dpm/common/urls.py
from django.urls import path, include

urlpatterns = [
    path("accounts/", include("apps.accounts.urls", namespace="accounts")),
    path("", include("apps.passwords.urls", namespace="passwords"))
]

dpm/apps/accounts/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from django.contrib.auth import get_user_model
from django.utils import timezone

from apps.accounts.managers import BaseUserManager

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)
    last_online = models.DateTimeField(null=True)

    objects = BaseUserManager()

    USERNAME_FIELD = "email"

class Folder(models.Model):
    uid = models.AutoField(primary_key=True)
    name = models.CharField(max_length=32)

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="folders")

    class Meta:
        unique_together = ("user", "name")

    def __str__(self):
        return f"{self.name}"

@receiver(post_save, sender=User)
def create_folder(sender, instance, created, **kwargs):
    if created:
        Folder.objects.create(name="No Folder", user=instance)

dpm/apps/accounts/forms.py
from django import forms
from django.contrib.auth.models import Group
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from apps.accounts.models import User

class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label="Password", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("email", "password")

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()

        return user

dpm/apps/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, DeleteView
from django.urls import reverse, reverse_lazy

from apps.accounts.models import User
from apps.accounts.forms import RegistrationForm

class RegistrationView(CreateView):
    template_name = "registration/register.html"
    form_class = RegistrationForm

    def get_context_data(self, *args, **kwargs):
        context = super(RegistrationView, self).get_context_data(*args, **kwargs)
        context["next"] = self.request.GET.get("next")

        return context

    def get_success_url(self):
        next_url = self.request.POST.get("next")
        success_url = reverse("accounts:login")
        if next_url:
            messages.add_message(self.request, messages.SUCCESS, "Account successfully registered.")
            success_url += "?next={}" % next_url

        return success_url

class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = User
    template_name = "confirm_delete.html"
    success_url = reverse_lazy("accounts:login")
    
    def get_object(self, queryset=None):
        user = self.request.user

        return user 

dpm/apps/accounts/templates/confirm_delete.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-2-5">
        <div class="container">
            <div class="container-header">
                <p>SETTINGS</p>
            </div>
            <div class="container-main">
                <input class="fit-input" type="text" placeholder="Search Settings" />
                <div class="folders">
                    <ul>
                        <li><a href="#">Manage Account</a></li>
                        <li><a href="#">Options</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="col-7">
        <div class="header">
            <h2>My Account</h2>
        </div>
        <form method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-lg btn-danger">Delete Account</button>
            <p class="small">This action is permanent.</p>
        </form>
    </div>
    <div class="col-2-5">
    </div>
</div>
{% endblock content %}

dpm/common/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        {% load static %}

        <link rel="stylesheet" type="text/css" href="{% static 'styles/main.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'styles/fonts.css' %}">

        <script src="{% static 'js/modals.js' %}"></script>
        <script src="{% static 'js/util.js' %}"></script>
        <script src="{% static 'js/particles.js' %}"></script>

        <title>DjangoPasswordManager</title>
    </head>
    <body>
        <div id="particles-js">
        </div>
        <header>
            {% if messages %}
                {% for message in messages %}
                    <div class="main-flashes">
                        <div class="flash-message flash-{{ message.tags }}">
                            <p>{{ message }}</p>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
            <nav>
                <div class="navbar">
                    <div class="nav-section">
                        <ul>
                            <li class="left"><a class="nav-link active" href="{% url 'passwords:vault' %}">My Vault</a></li>
                            {% if user.is_authenticated %}
                                <li class="left"><a class="nav-link" href="#generator">Generator</a></li>
                                <li class="left"><a class="nav-link" href="{% url 'accounts:delete_account' %}">Settings</a></li>
                            {% endif %}
                        </ul>
                    </div>
                    <div class="nav-section">
                        <ul>
                            {% if user.is_authenticated %}
                                <li class="right"><a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a></li>
                                <li class="right"><a class="nav-link" href="{% url 'accounts:delete_account' %}">{{ user.email }}</a></li>
                            {% else %}
                                <li class="right"><a class="nav-link" href="{% url 'accounts:register' %}">Register</a></li>
                                <li class="right"><a class="nav-link" href="{% url 'accounts:login' %}">Login</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <main>
            {% block content %}{% endblock content %}
        </main>
    </body>
    <script>
     /* particlesJS.load(@dom-id, @path-json, @callback (optional)); */
    particlesJS.load('particles-js', "{% static 'js/particles.json' %}", function() {
        console.log('callback - particles.js config loaded');
    });
    </script>
</html>